networks:
  airflow_network:
    external: true
    name: airflow_network_terraform

volumes:
  postgres-db-volume:
    external: true
    name: postgres-db-volume-terraform
  mlflow_artifacts:
    external: true
    name: mlflow-artifacts-terraform
  airflow_data:
    external: true
    name: airflow-data-terraform
  grafana_data:
    external: true
    name: grafana-data-terraform

x-airflow-common:
  &airflow-common
  build:
    context: ./airflow
    dockerfile: Dockerfile
  environment:
    &airflow-common-env
    AIRFLOW__API_AUTH__JWT_SECRET: ${AIRFLOW_JWT_SECRET}
    AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${AIRFLOW_POSTGRES_DB}
    AIRFLOW_CONFIG: '/opt/airflow/config/airflow.cfg'
    AIRFLOW_CONN_AIRLINES: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${AIRLINES_POSTGRES_DB}"
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
    AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__MIN_SERIALIZED_DAG_FETCH_INTERVAL: 10
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__CORE__TEST_CONNECTION: 'Enabled'
    AIRFLOW__CORE__EXECUTION_API_SERVER_URL: 'http://airflow-api-server:8080/execution/'
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${AIRFLOW_POSTGRES_DB}
    AIRFLOW__API__SECRET_KEY: ${AIRFLOW_API_SECRET_KEY}
    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
    AIRFLOW__LOGGING__REMOTE_LOGGING: 'false'
    AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER: ''
    AIRFLOW__LOGGING__TASK_LOGGER: 'airflow.utils.log.task_handler.DbTaskHandler'
    AIRFLOW__LOGGING__HANDLER: 'airflow.utils.log.task_handler.DbTaskHandler'
    MLFLOW_TRACKING_URI: "${MLFLOW_API_URL}"
    PYTHONPATH: "${AIRFLOW_PROJ_DIR:-.}/plugins"
    _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS:-}
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/config:/opt/airflow/config
    - ./airflow/plugins:/opt/airflow/plugins
    - mlflow_artifacts:/mlflow/artifacts
    - ./airflow/data:/opt/airflow/data
  networks:
    - airflow_network
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    &airflow-common-depends-on
    redis:
      condition: service_healthy
    postgres:
      condition: service_healthy
    selenium:
      condition: service_healthy

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${AIRFLOW_POSTGRES_DB}
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
      - ./airflow/config:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      retries: 5
    networks:
      - airflow_network
    restart: always

  redis:
    image: redis:7.2-bookworm
    container_name: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
    networks:
      - airflow_network
    restart: always

  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium
    shm_size: 2gb
    networks:
      - airflow_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4444/wd/hub/status || exit 1"]
      interval: 30s
    restart: always

  mlflow:
    build:
      context: ./mlflow
      dockerfile: Dockerfile
    container_name: mlflow
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_BACKEND_STORE_URI=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/mlflow
      - MLFLOW_ARTIFACT_ROOT=/mlflow/artifacts
    volumes:
      - mlflow_artifacts:/mlflow/artifacts
    networks:
      - airflow_network
    command: >
      mlflow server
      --backend-store-uri postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/mlflow
      --default-artifact-root /mlflow/artifacts
      --host 0.0.0.0
      --port 5000
      --allowed-hosts "*"
      --cors-allowed-origins "*"
    depends_on:
        postgres:
          condition: service_healthy
    restart: always

  airflow-api-server:
    <<: *airflow-common
    container_name: api-server
    command: api-server
    ports:
      - "8080:8080"
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    container_name: scheduler
    command: scheduler
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
    restart: always

  airflow-worker:
    <<: *airflow-common
    container_name: worker
    command: celery worker
    environment:
      <<: *airflow-common-env
      AIRFLOW__CELERY__WORKER_CONCURRENCY: 8
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
    restart: always

  airflow-init:
    <<: *airflow-common
    container_name: init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        # Gestion des dossiers et permissions
        mkdir -p /mlflow/artifacts
        chown -R "50000:0" /mlflow/artifacts
        chmod -R 775 /mlflow/artifacts
        mkdir -p /opt/airflow/{dags,plugins,config,logs,data}
        chown -R "50000:0" /opt/airflow/

        echo "Running airflow db migrate..."
        airflow db migrate

        # Creation de l'utilisateur admin (nécessaire si non présent)
        airflow users create --username admin --firstname admin --lastname admin --role Admin --email admin@example.com --password admin || true

        airflow variables import /opt/airflow/config/variables.json
        airflow pools set selenium_pool ${SELENIUM_POOL_SIZE} "Pool pour limiter les sessions Selenium"

        airflow dags reserialize
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
      SELENIUM_POOL_SIZE: ${SELENIUM_POOL_SIZE}
    user: "0:0"
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: api
    volumes:
      - ./api:/app/api
      - mlflow_artifacts:/mlflow/artifacts
    ports:
      - "8000:8000"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      AIRLINES_POSTGRES_DB: ${AIRLINES_POSTGRES_DB}
      MLFLOW_API_URL: ${MLFLOW_API_URL}
      MODEL_NAME: ${MODEL_NAME}
    networks:
      - airflow_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres-exporter
    ports:
      - "9187:9187"
    environment:
      DATA_SOURCE_NAME: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${AIRLINES_POSTGRES_DB}?sslmode=disable"
    networks:
      - airflow_network
    restart: always

  pushgateway:
    image: prom/pushgateway:latest
    container_name: pushgateway
    ports:
      - "9091:9091"
    networks:
      - airflow_network
    restart: always

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - airflow_network
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - airflow_network
    depends_on:
      - pushgateway
      - cadvisor
      - postgres-exporter
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/etc/grafana/dashboards:ro
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    networks:
      - airflow_network
    depends_on:
      - prometheus
    restart: always

  init-permissions:
    image: alpine
    container_name: init-permissions
    user: "0:0"
    volumes:
      - mlflow_artifacts:/mlflow/artifacts
      - ./airflow/data:/airflow_data
    command: >
      sh -c "chmod -R 777 /mlflow/artifacts && chmod -R 777 /airflow_data"

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - airflow_network