global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'docker-metrics'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'fastapi-metrics'
    static_configs:
      - targets: ['api:8000']